# frozen_string_literal: true

source "https://rubygems.org"

rails_version = (ENV["RAILS_VERSION"] || "7.1.1").to_s

gem "rake", "~> 13.1"
gem "rack-cors", ">= 2.0.2"
gem "sprockets"
gem "sprockets-rails"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
if rails_version != "main"
  gem "actioncable", ">= 7.1.3.1", rails_version
  gem "actionview", ">= 7.1.2", rails_version
  gem "activemodel", rails_version
  gem "activesupport", rails_version
  gem "railties", ">= 7.1.3.1", rails_version
else
  git "https://github.com/rails/rails", ref: "main" do
    # rubocop:disable Bundler/DuplicatedGem
    gem "actioncable", ">= 7.1.3.1"
    gem "actionview", ">= 7.1.2"
    gem "activemodel"
    gem "activerecord"
    gem "activesupport"
    gem "railties", ">= 7.1.3.1"
    # rubocop:enable Bundler/DuplicatedGem
  end
end

eval_gemfile "gemfiles/kuby.gemfile"

# Use Puma as the app server
gem "puma", "~> 6.4.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

gem "primer_view_components", path: "../"
gem "view_component", '>= 3.1.0'
gem "lookbook", "~> 2.2.0"

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring", "~> 4.1"
  gem "spring-watcher-listen", "~> 2.1"
  gem "hotwire-livereload", "~> 1.3", ">= 1.3.1"
  # Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
  gem "importmap-rails", ">= 2.0.0"

  # Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
  gem "turbo-rails", ">= 2.0.0"

  # Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
  gem "stimulus-rails", ">= 1.3.1"

  gem "foreman"

  gem "listen"
end
